### ISSUE TITLE
reply/reply all boxes slide into final layout

### ISSUE THREAD

**Issue by Chris115v** [protz/GMail-Conversation-View#893]
Using 201411090754-master.xpi with TB 34b1. Drawing of the message area seems a bit slow, or at least changed. If there are reply and reply all boxes, they first draw full width one on top of the other, and then a blip later they slide in next to each other. Happens quickly, so it's still fully usable.

**Comment by protz** [comment]
Hi,

Sorry about the delay. I've been super busy and I don't even have enough time to keep the addon from being severely broken, so I'm going to focus on fixing the most urgent bugs from now.

Since this is a non-fatal issue, I'm closing this, but do reopen if you've got a patch / suggested fix.

Thanks for understanding,

Jonathan
