### ISSUE TITLE
It should be possible to enable/disable Conversations selectively for each configured account

### ISSUE THREAD

**Issue by Cris70** [protz/GMail-Conversation-View#920]
Just as the subject says, I would like to be able to selectively enable/disable Thunderbird Conversations for each configured account.
Actually, Thunderbird Conversations is only really worthy when associated with a GMail account. If you have other accounts, it would be very nice to be able to disable it selectively.
e.g. I have a certified email account that I would like to use with the ThunderPEC Thunderbird extension. However ThunderPEC is incompatible with Thunderbird Conversations.
I can configure ThunderPEC to be enabled only for the certified email account, but I cannot configure Thunderbird Conversation to be _disabled_ for that account.

**Comment by pianoslum** [comment]
Why is this addon only worth with a GMail account? ;-)

I think what you want is not possible; respectively I don't think it's worth the struggle to implement this. You could use different accounts in Windows as AddOns can be installed seperately for every user.

Another way would be to make your AddOn compatible with conversations...

**Comment by Cris70** [comment]
ThunderPEC is not "my" addon. It is simply an addon I use, but unfortunately I don't have any influence on development.
Anyway, ThunderPEC can be selectively enabled for one/many/all accounts, so why shouldn't it be possible for this addon?

**Comment by protz** [comment]
@Cris70 I, quite unfortunately, need to side with @pianoslum on that one. I hardly have time to maintain this addon, so any extra feature has a complexity cost that I can't afford. There's already an option in View > Conversation View that allows you to disable it in one click of a menu, and I'm afraid that's the best I can offer right now.

Again, if you have specific pain points that you believe are worth fixing, so that you are happy with using the addon on all of your accounts, feel free to file more issues!

Thanks for understanding,

Jonathan
