### ISSUE TITLE
Many debug messages

### ISSUE THREAD

**Issue by pianoslum** [protz/GMail-Conversation-View#948]
I noticed some recurring debug messages. This is pretty minor, but if we have time left we could try to get rid of them:

* No chrome package registered for chrome://calendar/skin/cal-icon32.png (though there is no reference to "Conversations", this only seems to occur when the AddOn is installed. This message also pops up very often)

* Timestamp: 14.04.2015 01:04:53
Warning: Expected color but found '-moz-oddtreerowtext'.  Error in parsing value for 'color'.  Declaration dropped.
Source File: chrome://conversations/skin/tokeninput.css
Line: 38, Column: 11
Source Code:
    color: -moz-oddtreerowtext;

* Timestamp: 14.04.2015 01:04:53
Warning: Error in parsing value for 'font-style'.  Declaration dropped.
Source File: chrome://conversations/skin/tokeninput.css
Line: 113, Column: 16
Source Code:
    font-style: none;

* Timestamp: 14.04.2015 01:04:53
Warning: Unknown property '-moz-box-shadow'.  Declaration dropped.
Source File: chrome://conversations/skin/print.css
Line: 51, Column: 17
Source Code:
  -moz-box-shadow: 0 0 0 transparent;

* No chrome package registered for chrome://conversations/content/icon.png

* When switching between messages to quickly (being offline), I sometimes get something like "You failed to call signal enough times. Bad developer! Go fix your code!". While this pleases my masochistic side, a little more clarity what is actually wrong would be nice ;-) This occurs very infrequently, however.

**Comment by protz** [comment]
* We should generate (in the template) the lightning bar only when lightning is detected to be installed. That's the reason for the cal-icon32.png issue.
* Indeed, it seems that this special mozilla color does not exist. What would be the right replacement? I'm unsure.
* Remove the declaration.
* Switch to box-shadow (need to actually read MDN because the syntax changed)
* Don't know. The file seems to exist...
* Yeah, need to investigate that, but that's probably super hard to fix so I would rather file a separate issue. Probably the same issue that's causing the incompatibility with MailSummaries.

**Comment by pianoslum** [comment]
I read that you can just put a file called icon.png in the root dir and there's no need anymore to register it (in content) somewhere. So I deleted the file and the reference and everything seems to be fine (warning is gone, too)!

I removed `font-style` and changed `moz-box-shadow` - seems to be working.

The only thing google finds when searching for `-moz-oddtreerowtext` is #867, so @xi do you know anything about it?

About calendar.png: I see it's declared in stub.xhtml - can I just remove it or how could it be done?

**Comment by protz** [comment]
Super.

- mxr.mozilla.org finds nothing for moz-oddtreerowtext, so if everything 
looks good, maybe we should just get rid of it, unless of course @xi 
comes up with a suggestion
- calendar.png is present when lightning is installed, so maybe it would 
be wise to 1) detect in message.js (once and for all) if lightning is 
installed, and then 2) pass in tmplData a flag that says "generate 
lightning stuff or not" so that 3) the template can contain something 
like {{if lightningInstalled}}....calendar.png...{{/if}}

Don't know if that's clear :)

**Comment by xi** [comment]
> The only thing google finds when searching for -moz-oddtreerowtext is #867, so @xi do you know anything about it?

I have taken most of the colors from [mozilla developer docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Mozilla_Extensions) but it seems like this was a case of lazy extrapolation. I did certainly not have any super secret inside knowledge when I use `-moz-oddtreerowtext`.

**Comment by pianoslum** [comment]
Ok, I have no insight in this whole CSS thing. Would it be ok if I just deleted the `-moz-oddtreerowtext` or should I use something different?
