### ISSUE TITLE
Fix callers of msgHdrsDelete

### ISSUE THREAD

**Issue by Dimas-sc** [protz/GMail-Conversation-View#956]
I've updated to the 38 beta (Thunderbird next major version) and Conversation doesn't work. Is it planned to update the addon to work with it?

**Comment by pianoslum** [comment]
Well it certainly *should* work. Did you use the new 2.9 version? Is there an error message in the error console? Which OS do you use? Some information would be helpful ;-)

**Comment by protz** [comment]
Did you 1) make sure Conversations has upgraded to the latest version 
and 2) restart Thunderbird?

**Comment by Dimas-sc** [comment]
Hi,
Sorry for that, I guess it was not on the latest 2.9 version when I tried for the first time. Now the Conversation buttons appears but the "Delete this conversation" button doesn't work (it does nothing, without error message)

**Comment by TheMegamind** [comment]
Since upgrading to Thunderbird Conversations 2.9.0 on Thunderbird 38.0 I have noted that the "Delete this Conversation" button that is present when reading any individual button does not function.  I have to right click on the email and choose delete to send it to trash.  The others buttons appear to work as intended.

The follow error appears in the error console:

Error: TypeError: pending[Symbol.iterator] is not a function
Source File: resource://conversations/modules/stdlib/msgHdrUtils.js
Line: 270

**Comment by pianoslum** [comment]
That sounds like a bug introduced by me (substituting for each). Sorry for that. Right now, I have very limited internet access, so @protz could you look at that?

In 2 weeks I could do this as well; we could think about a "hotfix" if more problems occur...

**Comment by protz** [comment]
I'll look into it. Thanks.

**Comment by protz** [comment]
http://jonathan.xulforum.org/files/gcv-nightlies/201505070706-2.9+.xpi does this version fix it?

**Comment by TheMegamind** [comment]
Yes.

**Comment by TheMegamind** [comment]
Oops, no it doesn't.  I spoke too soon.  I wasn't in the right view.

**Comment by protz** [comment]
Ok, I'm fairly busy atm but I'll try to debug this soon.

**Comment by TheMegamind** [comment]
Do you know when this fix will be released?

**Comment by msprotz** [comment]
The latest 2.9+ version at http://jonathan.xulforum.org/files/gcv-nightlies/ fixes it; I just need to push it for a new release... will try to do that this week.
