### ISSUE TITLE
Quick-reply message is being destroyed when someone replies into the chain during typing

### ISSUE THREAD

**Issue by rayrapetyan** [protz/GMail-Conversation-View#960]
1. Select message chain with multiple participants (left click) -> chain will be scrolled to the bottom in the lower window.
2. Hit "Reply all" (a button with a shape of an old-school "Enter" key) -> a quick reply area will open.
3. Start to type something.
4. Now, if someone replies to this chain while you are typing - your message will be completely destroyed.
This is very annoying as could destroy many hours of work at once.

'"Reply all" in a new window' feature suffers this situation.

**Comment by protz** [comment]
This is #730, and is quite unfortunately a known issue. In the event that you should know how to fix this, any help would be more than welcome! I suspect the fix, though, depends on enabling quick reply for every message in the conversation, so that the focused element isn't removed from the DOM, and keeps focus.

**Comment by RalfJung** [comment]
#730 is about accidentally triggering shrotcut actions when a new message comes in while typing. However, this bug here is different - it is about *losing* the entire content of the QuickReply field, the partially written message, when a new message comes in. This loss is not caused by a shortcut being accidentally triggered, or focus being lost. It is rather triggered by, somehow, the Conversations plugin not being able to find the old, partially written message anymore when a new one comes in.

So, these two seem to be very different bugs to me. Or did I miss something?
