### ISSUE TITLE
Feature Request: Text instead of icons

### ISSUE THREAD

**Issue by DaveJarvis** [protz/GMail-Conversation-View#964]
For people who are unfamiliar with them, the following icons are indecipherable:

![icons](https://cloud.githubusercontent.com/assets/2131950/7971171/bb4e3aa6-09f7-11e5-809a-ebd4c55df0e2.png)

While the tool-tip is helpful, there should be an option to revert to written text labels. For example, I would like to request the following feature:

1. Right-click on the toolbar.
2. Select Customize...
3. Check "Use text labels" (or uncheck "Use icon labels").

**Comment by protz** [comment]
Hi,

Thanks for the feedback. I'm afraid I have to say no to another option: there's already 1536 possible combinations in the options panel of Conversations. I'm only testing one of these: doubling that will only make things worse. Your feedback seems to suggest that the icons are not recognizable enough.

What platform are you using? On Windows, this matches the set of known icons from the standard message reader. If you're on Linux or Mac, then perhaps these icons are not the standard ones. If this is the case, then I'd validate a bug report about using the platform-standard icons for these buttons so that it's less confusing.

Text is out of the question, since in vertical mode, this bar is super crowded already.

You can either:
* open up a new bug report for using platform specific icons, if that's what's bugging you, or
* open up a new bug report for improving the UI of the top bar (e.g. use two lines when things are too crowded, which would in turn allow us to have text on these buttons).

In any case, I would take patches for any of the two issues above, but not fix them myself.

Thanks,

Jonathan
